spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotline
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  error:
    include-message: always
    include-binding-errors: always