spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotline
    username: root
    password: 2036205
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 3000
  error:
    include-message: always
    include-binding-errors: always
